// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from 'next/dynamic';

export const components = {
  call_to_action: dynamic(() => import('./CallToAction')),
  content_image_slice: dynamic(() => import('./ContentImageSlice')),
  features: dynamic(() => import('./Features')),
  hero: dynamic(() => import('./Hero')),
  rich_text_slice: dynamic(() => import('./RichTextSlice')),
  section_headers: dynamic(() => import('./SectionHeaders')),
  timeline: dynamic(() => import('./Timeline')),
};
