// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from 'next/dynamic';

export const components = {
  blog_list: dynamic(() => import('./BlogList')),
  call_to_action: dynamic(() => import('./CallToAction')),
  content_image_slice: dynamic(() => import('./ContentImageSlice')),
  faqs: dynamic(() => import('./Faqs')),
  features: dynamic(() => import('./Features')),
  hero: dynamic(() => import('./Hero')),
  lesson_rick_text: dynamic(() => import('./LessonRickText')),
  pricing_table: dynamic(() => import('./PricingTable')),
  rich_text_slice: dynamic(() => import('./RichTextSlice')),
  section_headers: dynamic(() => import('./SectionHeaders')),
  stats: dynamic(() => import('./Stats')),
  testimonials: dynamic(() => import('./Testimonials')),
  timeline: dynamic(() => import('./Timeline')),
};
