// Code generated by Prismic. DO NOT EDIT.

import BlogList from "./BlogList";
import CallToAction from "./CallToAction";
import ContentImageSlice from "./ContentImageSlice";
import Discounts from "./Discounts";
import Faqs from "./Faqs";
import Features from "./Features";
import Hero from "./Hero";
import ImageGrid from "./ImageGrid";
import LessonRickText from "./LessonRickText";
import PricingTable from "./PricingTable";
import RichTextSlice from "./RichTextSlice";
import SectionHeaders from "./SectionHeaders";
import Stats from "./Stats";
import Testimonials from "./Testimonials";
import Timeline from "./Timeline";

export const components = {
	blog_list: BlogList,
	call_to_action: CallToAction,
	content_image_slice: ContentImageSlice,
	discounts: Discounts,
	faqs: Faqs,
	features: Features,
	hero: Hero,
	image_grid: ImageGrid,
	lesson_rick_text: LessonRickText,
	pricing_table: PricingTable,
	rich_text_slice: RichTextSlice,
	section_headers: SectionHeaders,
	stats: Stats,
	testimonials: Testimonials,
	timeline: Timeline
};