import '../styles/navbar.scss';
import './global.scss';
import { Raleway } from 'next/font/google';
import { Suspense } from 'react';

import { UIProvider } from '@rocket-house-productions/hooks';
import { GoogleAnalytics } from '@rocket-house-productions/util';
import { PrismicPreview } from '@prismicio/next';
import { repositoryName } from '@/prismicio';
import { ClerkProvider } from '@clerk/nextjs';

const raleway = Raleway({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-raleway',
});

export const metadata = {
  title: 'Welcome to kids-guitar-dojo',
  description: 'Generated by create-nx-workspace',
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <ClerkProvider
      appearance={{
        layout: {
          logoImageUrl:
            'https://deploy-preview-1--kids-guitar-dojo.netlify.app/_next/image?url=%2F_next%2Fstatic%2Fmedia%2Flogo.8b1fb0cd.png&w=128&q=75',
        },
      }}>
      <UIProvider>
        <html lang="en" className={`${raleway.variable} font-sans`} suppressHydrationWarning>
          <body className={'bg-background min-h-screen font-sans antialiased'}>
            {children}
            {/* Analytics */}
            <Suspense>
              <GoogleAnalytics GA_MEASUREMENT_ID={process.env.NEXT_GOOGLE_ANALYTICS_ID || ''} />
            </Suspense>

            {/* Preview */}
            <PrismicPreview repositoryName={repositoryName} />
          </body>
        </html>
      </UIProvider>
    </ClerkProvider>
  );
}
