import './global.css';
import {Suspense} from 'react';

import {BackToTop} from '@rocket-house-productions/layout';
import {GoogleAnalytics} from '@rocket-house-productions/util';

export const metadata = {
  title: 'Welcome to kids-guitar-dojo',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}

      {/* BackToTop */}
      <BackToTop/>
      <Suspense>
        <GoogleAnalytics GA_MEASUREMENT_ID={process.env.NEXT_GOOGLE_ANALYTICS_ID || ''}/>
      </Suspense>
      </body>
    </html>
  );
}
